# Generated by Django 4.1.3 on 2023-11-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.IntegerField(default=1)),
                ('prefectures', models.CharField(max_length=128)),
                ('municipalities', models.CharField(max_length=128)),
                ('name1', models.CharField(max_length=128)),
                ('name2', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=128)),
                ('email_address', models.CharField(max_length=128)),
                ('arrival_date', models.IntegerField(default=1)),
            ],
        ),
    ]
